### ISSUE TITLE
Map Marking on Double Click

### ISSUE THREAD

**Issue by rifkidocs** [play14team/strapi-plugin-map-field#5]
Is there a way to achieve accurate map marking when performing a double click, ensuring that the marker accurately corresponds to the clicked area rather than the closest geolocated point?

**Comment by claudiobgit** [comment]
> Is there a way to achieve accurate map marking when performing a double click, ensuring that the marker accurately corresponds to the clicked area rather than the closest geolocated point?

This feature woul be really useful as it would permit both the 'closest to' and the 'precise' geolocations. I've checked through all the available plugins and couldn't find anything yet to achieve this.

**Comment by cpontet** [comment]
Hi, sorry for the late response. 
I don't think I can do anything about the accuracy of the double click. I think it really depends on the precision of the geolocalization of OpenStreetMap.

**Comment by claudiobgit** [comment]
> [...] I think it really depends on the precision of the geolocalization of OpenStreetMap.

Maybe I didn't explain it correctly but I think the question from @rifkidocs was not about the accuracy of OSM geolocalization (that is pretty awesome btw) but more on the possibility of the marker to also point a lat/lon coordinate and not only snap to the closest POI. This feature would permit users to also record whatever X,Y point on map, whether there is a close POI or not. A toggle button to enable or disable snapping would be killer. Hope this made it more clear.

**Comment by enzobrunii** [comment]
You can check out this fork where the coordinates are overwritten to place the marker at the location you clicked: [Fork](https://github.com/enzobrunii/strapi-plugin-map-field/commit/616f581a270181560fb69106505a64afe34dfca6).

To update your package.json, replace the strapi-plugin-map-field entry with:

```
"strapi-plugin-map-field": "https://github.com/enzobrunii/strapi-plugin-map-field.git
```

**Comment by claudiobgit** [comment]
That's exactly what I was looking for @enzobrunii ! Will check it out asap. Thanks

**Comment by claudiobgit** [comment]
It works perfectly.
